accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
]
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]
ignore-dev-dependencies = true
private = { ignore = true }

[cbindgen]
accepted = ["MPL-2.0"]
